[project]
authors = ["Liel Amar <liel@lielamar.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "neural-networks"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.12.6,<4"
numpy = ">=2.1.1,<3"
ruff = ">=0.6.8,<0.7"
pixi-pycharm = ">=0.0.6,<0.0.7"
matplotlib = ">=3.9.2,<4"

[pypi-dependencies]
python-mnist = "==0.7"
